**Data Type Validation**

In [ ]:
import pandas as pd

df = pd.read_csv('/content/sample_data/part2.csv', index_col=['Unnamed: 0'])
df_copy = df.copy()

In [ ]:
df_copy.head()

,order id,date,status,fulfilment,sales channel,ship-service-level,style,sku,category,size,asin,courier status,qty,currency,amount,ship-city,ship-state,ship-postal-code,ship-country,b2b
0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,B09KXVBD7Z,Unknown,0,INR,647.62,MUMBAI,MAHARASHTRA,400081,IN,False
1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,B09K3WFS32,Shipped,1,INR,406.00,BENGALURU,KARNATAKA,560085,IN,False
2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,B07WV4JV4D,Shipped,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210,IN,True
3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,B099NRCT7B,Unknown,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008,IN,False
4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,B098714BZP,Shipped,1,INR,574.00,CHENNAI,TAMIL NADU,600073,IN,False

Firstly, let's display each column type

In [9]:
df_copy.dtypes

order id               object
date                   object
status                 object
fulfilment             object
sales channel          object
ship-service-level     object
style                  object
sku                    object
category               object
size                   object
asin                   object
courier status         object
qty                     int64
currency               object
amount                float64
ship-city              object
ship-state             object
ship-postal-code        int64
ship-country           object
b2b                      bool
dtype: object

**1. Date types** <br>
My first suspect is 'date' column that for now stores object type. Type should be converted into DataType.

In [17]:
df_copy['date'] = pd.to_datetime(df_copy['date']).dt.date
type(df_copy['date'].iloc[0])

datetime.date

**2. Numeric Types** <br>
Let's review numeric values.

In [22]:
df_copy.dtypes

order id               object
date                   object
status                 object
fulfilment             object
sales channel          object
ship-service-level     object
style                  object
sku                    object
category               object
size                   object
asin                   object
courier status         object
qty                     int64
currency               object
amount                float64
ship-city              object
ship-state             object
ship-postal-code        int64
ship-country           object
b2b                      bool
dtype: object

In [23]:
df_copy.head()

,order id,date,status,fulfilment,sales channel,ship-service-level,style,sku,category,size,asin,courier status,qty,currency,amount,ship-city,ship-state,ship-postal-code,ship-country,b2b
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,B09KXVBD7Z,Unknown,0,INR,647.62,MUMBAI,MAHARASHTRA,400081,IN,False
1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,B09K3WFS32,Shipped,1,INR,406.00,BENGALURU,KARNATAKA,560085,IN,False
2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,B07WV4JV4D,Shipped,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210,IN,True
3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,B099NRCT7B,Unknown,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008,IN,False
4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,B098714BZP,Shipped,1,INR,574.00,CHENNAI,TAMIL NADU,600073,IN,False

All numeric values are stored correctly.

**3. Memory & efficiency improvement - Object -> Categorical values** <br>
Firstly let's show how many unique values each column contains.

In [24]:
df_copy.nunique()

order id              120378
date                      91
status                    13
fulfilment                 2
sales channel              2
ship-service-level         2
style                   1377
sku                     7195
category                   9
size                      11
asin                    7190
courier status             4
qty                       10
currency                   1
amount                  1411
ship-city               8956
ship-state                70
ship-postal-code        9460
ship-country               1
b2b                        2
dtype: int64

Columns with a relatively small number of unique values are good candidates for conversion to the categorical data type.

Converting such columns to category can significantly reduce memory usage and improve performance, especially when working with large datasets. This optimization is particularly useful when columns represent repeated labels or discrete categories rather than free-text values. My main suspects are : status, fulfilment, ship-service-level, category, size, courier status, currency, ship-state, ship-country

In [27]:
df_copy['status'] = df_copy['status'].astype('category')
df_copy['fulfilment'] = df_copy['fulfilment'].astype('category')
df_copy['ship-service-level'] = df_copy['ship-service-level'].astype('category')
df_copy['category'] = df_copy['category'].astype('category')
df_copy['size'] = df_copy['size'].astype('category')
df_copy['courier status'] = df_copy['courier status'].astype('category')
df_copy['currency'] = df_copy['currency'].astype('category')
df_copy['ship-state'] = df_copy['ship-state'].astype('category')
df_copy['ship-country'] = df_copy['ship-country'].astype('category')

We may also see that column : 'b2b' contains only boolean values.

In [28]:
df_copy['b2b'] = df_copy['b2b'].astype('boolean')

In [29]:
# final check
df_copy.dtypes

order id                object
date                    object
status                category
fulfilment            category
sales channel           object
ship-service-level    category
style                   object
sku                     object
category              category
size                  category
asin                    object
courier status        category
qty                      int64
currency              category
amount                 float64
ship-city               object
ship-state            category
ship-postal-code         int64
ship-country          category
b2b                    boolean
dtype: object

In [30]:
df_copy.to_pickle('sample_data/part3.pkl')